"""
report_generator.py

Phase 13a: 리포트 생성 도구

PerformanceMetrics, ComparisonResult → Markdown/JSON 리포트 생성.
"""

from pathlib import Path
from typing import Optional
from datetime import datetime
import json

from .trade_analyzer import PerformanceMetrics
from .ab_comparator import ComparisonResult


class ReportGenerator:
    """리포트 생성 도구"""

    def generate_markdown(
        self,
        metrics: PerformanceMetrics,
        output_path: str,
        period: str = "Unknown"
    ):
        """
        Markdown 리포트 생성

        Args:
            metrics: 성과 지표
            output_path: 출력 파일 경로
            period: 기간 (예: "2026-01-01:2026-01-31")
        """
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)

        content = self._build_markdown_content(metrics, period)

        with open(output, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"✅ Markdown report generated: {output_path}")

    def _build_markdown_content(
        self,
        metrics: PerformanceMetrics,
        period: str
    ) -> str:
        """Markdown 내용 생성"""
        md = f"""# Trade Analysis Report

**Period**: {period}
**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} KST

---

## Summary

| Metric | Value |
|--------|-------|
| Total Trades | {metrics.total_trades} |
| Winrate | {metrics.winrate*100:.1f}% ({metrics.win_count} wins / {metrics.loss_count} losses) |
| Total PnL | ${metrics.total_pnl:.2f} USDT |
| Avg PnL per Trade | ${metrics.avg_pnl_per_trade:.2f} USDT |
| Profit Factor | {metrics.profit_factor:.2f} |
| Sharpe Ratio | {metrics.sharpe_ratio if metrics.sharpe_ratio else 'N/A'} |
| Sortino Ratio | {metrics.sortino_ratio if metrics.sortino_ratio else 'N/A'} |
| Max Drawdown | {metrics.max_drawdown_pct:.2f}% |
| Max Single Win | ${metrics.max_single_win:.2f} |
| Max Single Loss | ${metrics.max_single_loss:.2f} |
| Avg Holding Time | {metrics.avg_holding_time_seconds/3600:.2f} hours |
| Total Fees | ${metrics.total_fees_usd:.2f} USDT |
| Avg Slippage | ${metrics.avg_slippage_usd:.2f} USDT |

---

## Risk Metrics

| Metric | Value |
|--------|-------|
| Max Consecutive Wins | {metrics.max_consecutive_wins} |
| Max Consecutive Losses | {metrics.max_consecutive_losses} |
| PnL 95% CI | (${metrics.pnl_confidence_interval[0]:.2f}, ${metrics.pnl_confidence_interval[1]:.2f}) |

---

## Market Regime Breakdown

"""
        # Regime breakdown 섹션
        if metrics.regime_breakdown:
            md += "| Regime | Trades | Winrate | Total PnL | Avg PnL | Sharpe |\n"
            md += "|--------|--------|---------|-----------|---------|--------|\n"
            for regime, breakdown in metrics.regime_breakdown.items():
                sharpe_str = f"{breakdown.sharpe_ratio:.2f}" if breakdown.sharpe_ratio else "N/A"
                md += f"| {regime} | {breakdown.total_trades} | {breakdown.winrate*100:.1f}% | ${breakdown.total_pnl:.2f} | ${breakdown.avg_pnl:.2f} | {sharpe_str} |\n"
        else:
            md += "*No regime breakdown available.*\n"

        md += "\n---\n\n*Generated by CBGB Analysis Toolkit*\n"
        return md

    def generate_json(
        self,
        metrics: PerformanceMetrics,
        output_path: str,
        period: str = "Unknown"
    ):
        """
        JSON 리포트 생성

        Args:
            metrics: 성과 지표
            output_path: 출력 파일 경로
            period: 기간
        """
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)

        data = {
            "period": period,
            "generated_at": datetime.now().isoformat(),
            "metrics": {
                "total_trades": metrics.total_trades,
                "win_count": metrics.win_count,
                "loss_count": metrics.loss_count,
                "winrate": metrics.winrate,
                "total_pnl": metrics.total_pnl,
                "avg_pnl_per_trade": metrics.avg_pnl_per_trade,
                "max_drawdown_pct": metrics.max_drawdown_pct,
                "max_single_loss": metrics.max_single_loss,
                "max_single_win": metrics.max_single_win,
                "profit_factor": metrics.profit_factor,
                "sharpe_ratio": metrics.sharpe_ratio,
                "sortino_ratio": metrics.sortino_ratio,
                "avg_holding_time_seconds": metrics.avg_holding_time_seconds,
                "avg_slippage_usd": metrics.avg_slippage_usd,
                "total_fees_usd": metrics.total_fees_usd,
                "max_consecutive_wins": metrics.max_consecutive_wins,
                "max_consecutive_losses": metrics.max_consecutive_losses,
                "pnl_confidence_interval": metrics.pnl_confidence_interval,
            },
            "regime_breakdown": {}
        }

        # Regime breakdown 변환
        for regime, breakdown in metrics.regime_breakdown.items():
            data["regime_breakdown"][regime] = {
                "total_trades": breakdown.total_trades,
                "win_count": breakdown.win_count,
                "loss_count": breakdown.loss_count,
                "winrate": breakdown.winrate,
                "total_pnl": breakdown.total_pnl,
                "avg_pnl": breakdown.avg_pnl,
                "sharpe_ratio": breakdown.sharpe_ratio,
            }

        with open(output, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        print(f"✅ JSON report generated: {output_path}")

    def generate_comparison_report(
        self,
        result: ComparisonResult,
        output_path: str
    ):
        """
        A/B 비교 리포트 생성 (Markdown)

        Args:
            result: 비교 결과
            output_path: 출력 파일 경로
        """
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)

        md = f"""# A/B Comparison Report

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} KST

---

## Recommendation

**{result.recommendation}**

**Reasoning**: {result.reasoning}

**Statistically Significant**: {'✅ Yes (p < 0.05)' if result.is_significant else '❌ No (p >= 0.05)'}

---

## Performance Delta

| Metric | Before | After | Delta (Absolute) | Delta (%) |
|--------|--------|-------|------------------|-----------|
| Winrate | {result.before_metrics.winrate*100:.1f}% | {result.after_metrics.winrate*100:.1f}% | {result.winrate_delta_pct*100:+.1f}% | {result.winrate_change_pct:+.1f}% |
| Total PnL | ${result.before_metrics.total_pnl:.2f} | ${result.after_metrics.total_pnl:.2f} | ${result.pnl_delta_usd:+.2f} | {result.pnl_change_pct:+.1f}% |
| Sharpe Ratio | {result.before_metrics.sharpe_ratio if result.before_metrics.sharpe_ratio else 'N/A'} | {result.after_metrics.sharpe_ratio if result.after_metrics.sharpe_ratio else 'N/A'} | {result.sharpe_delta:+.2f} | {result.sharpe_change_pct:+.1f}% |
| Total Trades | {result.before_metrics.total_trades} | {result.after_metrics.total_trades} | {result.after_metrics.total_trades - result.before_metrics.total_trades:+d} | - |

---

## Statistical Test Results

### Winrate Test (Chi-square)

- **Statistic**: {result.winrate_test.statistic:.4f}
- **p-value**: {result.winrate_test.pvalue:.4f}
- **Significant**: {'✅ Yes' if result.winrate_test.pvalue < 0.05 else '❌ No'}

### PnL Test (t-test)

- **Statistic**: {result.pnl_test.statistic:.4f}
- **p-value**: {result.pnl_test.pvalue:.4f}
- **Significant**: {'✅ Yes' if result.pnl_test.pvalue < 0.05 else '❌ No'}
- **Mean Before**: ${result.pnl_test.mean_before:.2f}
- **Mean After**: ${result.pnl_test.mean_after:.2f}

---

## Before Metrics Summary

| Metric | Value |
|--------|-------|
| Total Trades | {result.before_metrics.total_trades} |
| Winrate | {result.before_metrics.winrate*100:.1f}% |
| Total PnL | ${result.before_metrics.total_pnl:.2f} |
| Avg PnL | ${result.before_metrics.avg_pnl_per_trade:.2f} |
| Profit Factor | {result.before_metrics.profit_factor:.2f} |

## After Metrics Summary

| Metric | Value |
|--------|-------|
| Total Trades | {result.after_metrics.total_trades} |
| Winrate | {result.after_metrics.winrate*100:.1f}% |
| Total PnL | ${result.after_metrics.total_pnl:.2f} |
| Avg PnL | ${result.after_metrics.avg_pnl_per_trade:.2f} |
| Profit Factor | {result.after_metrics.profit_factor:.2f} |

---

*Generated by CBGB Analysis Toolkit*
"""

        with open(output, 'w', encoding='utf-8') as f:
            f.write(md)

        print(f"✅ Comparison report generated: {output_path}")
